export const SITE_ADMIN_ROLE = 'SITE_ADMIN_ROLE'
export const SITE_MEDIC_ROLE = 'SITE_MEDIC_ROLE'
export const SITE_SUPPORT_ROLE = 'SITE_SUPPORT_ROLE'

export const GYM_ADMIN_ROLE = 'GYM_ADMIN_ROLE'
export const GYM_MANAGER_ROLE = 'GYM_MANAGER_ROLE'

export const GYM_COACH_ROLE = 'GYM_COACH_ROLE'
export const ATHLETE_ROLE = 'ATHLETE_ROLE'