export const GET_SENT_MESSAGES = 'GET_SENT_MESSAGES'
export const GET_RECEIVED_MESSAGES = 'GET_RECEIVED_MESSAGES'
export const GET_SENT_MESSAGES_ERROR = 'GET_SENT_MESSAGES_ERROR'
export const GET_RECEIVED_MESSAGES_ERROR = 'GET_RECEIVED_MESSAGES_ERROR'