export default {
    oneGym: null,
    gymName: null,
    gymStaff: null,
    adminGyms: null,
    globalGyms: null,
    gymForEdit: null,
    isSearching: false,
    adminUsername: null,
    gymControlsErr: null,
    deleteGymSuccess: false,
    searchedAdminGyms: null,
    searchedGlobalGyms: null,
    searchedGymCoaches: null,
    searchedGymManagers: null,
    searchedGymAthletes: null,
    gymCoachesSearching: false,
    gymManagersSearching: false,
    gymAthletesSearching: false,
}
